### PR TITLE
Fix intermittent fail for container and MQTT tests

### LINKED ISSUE #790: Mqtt tests in pipeline fails ofter due to disconnection with public mqtt broker
**Describe the bug**
As in tests the client connection is expected to be up and running, the tests fail if the client fails to disconnect. It is better to use a mock for the MQTT client.

**To Reproduce**
Run the pipeline or run the test for MQTT package locally

### PR DESCRIPTION
**Pull request by vipul-rawat**
Closes #790 

- Used mock Pubsub for container tests as an actual connection to MQTT was not required
- Changed the public broker from HiveMQ to EQMX for more stable connections

### CODE REVIEW

File: pkg/gofr/container/container_test.go [hunk 1]
```diff
@@ -159,16 +159,15 @@ func TestContainer_Close(t *testing.T) {
...
+	mockPubSub := &MockPubSub{}
 
 	mockDB.EXPECT().Close().Return(nil)
 	mockRedis.EXPECT().Close().Return(nil)
 
-	configs := map[string]string{
-		"PUBSUB_BACKEND": "MQTT",
-	}
-	c := NewContainer(config.NewMockConfig(configs))
+	c := NewContainer(config.NewMockConfig(map[string]string{}))
```
Comment (srijan-27) [inline pkg/gofr/container/container_test.go:167]: I think instead of empty config, we can use `nil`

**Review by srijan-27 — CHANGES_REQUESTED** [review]

**Review by srijan-27 — APPROVED** [review]
