### PR TITLE
Fix: Invalid ClickHouse Docs

### LINKED ISSUE #1081: Invalid Clickhouse godocs
godocs is selecting docs from the mocks generated, should be proper.

Along with this re-verify the other go-docs comments present in the package

https://pkg.go.dev/gofr.dev/pkg/gofr/datasource/clickhouse

Screenshot 2024-10-04 at 7 06 03 PM

### PR DESCRIPTION
**Pull request by FilledEther20**
## Pull Request

**Description:**

-   Closes #1081 is being tackled through this PR.
-   The update ensures that only the relevant Clickhouse package documentation is highlighted, improving both readability and maintainability of the code.

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

Thank You
Screenshot 2024-10-29 at 10 50 30 AM

### CODE REVIEW

File: pkg/gofr/datasource/clickhouse/clickhouse_test.go [hunk 1]
```diff
@@ -1,3 +1,6 @@
+//go:build exclude
+// +build exclude
```
Comment (ccoVeille) [inline pkg/gofr/datasource/clickhouse/clickhouse_test.go:2]: Not exactly related to this PR, but this syntax is outdated for a while I think.

https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md

@vipul-rawat @Umang01-hash Maybe an new issue/another PR could be created

What do you think?

Comment (ccoVeille) [reply pkg/gofr/datasource/clickhouse/clickhouse_test.go:2]: I've opened 

https://github.com/gofr-dev/gofr/issues/1175

Comment (Umang01-hash) [reply pkg/gofr/datasource/clickhouse/clickhouse_test.go:2]: Thank you for opening the issue. Marking this as resolved. Will remove it altogether when addressing the issue

**Review by aryanmehrotra — APPROVED** [review]
