### PR TITLE
Fix/add rest handlers put

### LINKED ISSUE #862: Fix AddRESTHandler PUT Method
**Describe the Issue**
Currently, In PUT Method, ID is required in both PathParam and Body, it should only use the one present in the pathParam.

Moreover, It gives the message Update Successfully in DB with ID is not passed in Body, but it doesn't get updated.

### LINKED ISSUE #1438: AddRESTHandlers PUT request doesn't work but returns a 200
**Describe the bug**
I'm following the add rest handlers guide and running into an issue: https://github.com/gofr-dev/gofr/tree/main/examples/using-add-rest-handlers

After sucesfully creating a user, when I attempt to perform an update (PUT) passing in the ID via a path e.g. http://localhost:9000/user/1, the response suggests that it was accepted i.e. a 200 response, but it did NOT update the resource. It looks like I need to explictly pass in the 'id' field in the json body, but I assume that should not be required if we've defined that in the path

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

```
PUT /user/1 HTTP/1.1
Content-Length: 57
Content-Type: application/json
Host: localhost:9000
User-Agent: HTTPie

{
  "name": "bob",
  "age": 10,
  "is_employted": false
}

HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization, Content-Type, x-requested-with, origin, true-client-ip, X-Correlation-ID
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 48
Content-Type: application/json
Date: Sun, 26 Jan 2025 15:29:54 GMT
X-Correlation-Id: c723949d80b098b01aac0c33b17b0b42

{"data":"user successfully updated with id: 1"}

```

2. The error is

```
GET /user/1 HTTP/1.1
Content-Type: application/json
Host: localhost:9000
User-Agent: HTTPie

HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization, Content-Type, x-requested-with, origin, true-client-ip, X-Correlation-ID
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 59
Content-Type: application/json
Date: Sun, 26 Jan 2025 15:33:00 GMT
X-Correlation-Id: 34e5c6357497b1a1a3b75bfbce99131a

{"data":{"id":1,"name":"fff","age":41,"isEmployed":false}}

```

**Expected behavior**
If the path contains the ID then I'd assume there should be no need to include it in the body

I'm basing that assumption on the docs: https://gofr.dev/docs/quick-start/add-rest-handlers

```
Update: /entity/{id} Updates an existing record identified by the {id} path parameter, based on data provided in a JSON request body.
```

### PR DESCRIPTION
**Pull request by Umang01-hash**
## Pull Request Template

**Description:**

-   Resolves #862 
- Resolves #1438 

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

**Review by coolwednesday — APPROVED** [review]

File: pkg/gofr/crud_handlers.go [hunk 1]
```diff
@@ -283,23 +283,36 @@ func (e *entity) Get(c *Context) (any, error) {
 
 func (e *entity) Update(c *Context) (any, error) {
 	newEntity := reflect.New(e.entityType).Interface()
+	id := c.Request.PathParam("id")
```
Comment (vipul-rawat) [inline pkg/gofr/crud_handlers.go:286]: We can have c.PathParam() to get Id

File: pkg/gofr/crud_handlers.go [hunk 2]
```diff
@@ -283,23 +283,36 @@ func (e *entity) Get(c *Context) (any, error) {
...
+		fieldValue := reflect.ValueOf(newEntity).Elem().Field(i)
 
-	id := c.PathParam("id")
+		if fieldName == e.primaryKey && isAutoIncrement {
+			convertedID, convErr := convertIDType(id, field.Type)
+			if convErr != nil {
+				return nil, fmt.Errorf("failed to convert ID: %w", convErr)
+			}
+
+			fieldValue.Set(reflect.ValueOf(convertedID))
```
Comment (vipul-rawat) [inline pkg/gofr/crud_handlers.go:310]: we might not need a conversion of the auto_increment id since it is always a integer, and we should be updating based on primary key and not always id

File: pkg/gofr/crud_handlers.go (hunk 1 above)
Comment (Umang01-hash) [reply pkg/gofr/crud_handlers.go]: changed

File: pkg/gofr/crud_handlers.go (hunk 2 above)
Comment (Umang01-hash) [reply pkg/gofr/crud_handlers.go]: ok done

File: pkg/gofr/crud_handlers_test.go [hunk 3]
```diff
@@ -520,7 +520,7 @@ func Test_UpdateHandler(t *testing.T) {
 			t.Run(dc.dialect+" "+tc.desc, func(t *testing.T) {
 				ctx := createTestContext(http.MethodPut, "/user", strconv.Itoa(tc.id), tc.reqBody, c)
 
-				mock.ExpectExec(dc.expectedQuery).WithArgs("goFr", true, tc.id).
+				mock.ExpectExec(dc.expectedQuery).WithArgs("goFr", true, strconv.Itoa(tc.id)).
```
[the remark this answers is not in the document]
Comment (Umang01-hash) [reply pkg/gofr/crud_handlers_test.go]: done

**Comment by coolwednesday** [comment]
@Umang01-hash, please add this issue to the PR . 
- https://github.com/gofr-dev/gofr/issues/1438

**Review by vipul-rawat — APPROVED** [review]
