### PR TITLE
Fix incorrect routing of commands to terminal execution when developing a CLI app using GoFr.

### LINKED ISSUE #1516: GoFr CLI's use of regex can lead to unintended command execution due to misleading pattern matches.
In cmd.go of GoFr, regex is used for pattern matching, which can sometimes lead to [unintended command execution](https://github.com/gofr-dev/gofr-cli/issues/41).

In the linked issue, the developer intended to run `gofr migrate create config_initial`, but the regex incorrectly matched "init" within "initial" to the `init` command of gofr-cli, resulting in the wrong command being executed. This behavior is unintended and should be corrected.

### PR DESCRIPTION
**Pull request by coolwednesday**
- Closes #1516 

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

**Review by Umang01-hash — APPROVED** [review]

File: pkg/gofr/cmd.go [hunk 1]
```diff
@@ -127,6 +124,17 @@ func AddHelp(helperString string) Options {
...
 func (cmd *cmd) addRoute(pattern string, handler Handler, options ...Options) {
+	// Define restricted characters
+	restrictedChars := "$^"
+
+	// Check if the pattern contains any restricted characters
+	for i := 0; i < len(pattern); i++ {
+		if strings.ContainsRune(restrictedChars, rune(pattern[i])) {
+			fmt.Println("found a restricted character in the command while registering with GoFr:", pattern[i])
+			return
+		}
```
Comment (aryanmehrotra) [inline pkg/gofr/cmd.go:135]: Document update for this?

**Review by aryanmehrotra — CHANGES_REQUESTED** [review]

**Review by aryanmehrotra — APPROVED** [review]
