### PR TITLE
Fixing sql mocks

### LINKED ISSUE #960: Unable to test all SQL database operations
Since we have HealthCheck in the interface, we are not able to assign sqlmock to the DB interface, due to which QueryRow and QueryRowContext cannot be tested

### PR DESCRIPTION
**Pull request by coolwednesday**
**Description:**
-  Closes #960 
-   Previously the mock was not able to mock Query, Queryrow, Select, Dialect, HealthCheck methods. Hence, replaced            MockGen generated sql mocks with go-mock-sql package in the mock container.
-   Added Mock functions for Select, Dialect, HealthCheck as they are extra methods added by GoFr's DB interface.
-  Corrected existing tests to use the new mocking behaviour of sql

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

### CODE REVIEW

File: pkg/gofr/container/container_test.go [hunk 1]
```diff
@@ -4,11 +4,11 @@ import (
 	"context"
 	"testing"
 
+	"go.uber.org/mock/gomock"
+
 	"github.com/gorilla/websocket"
 	"github.com/stretchr/testify/assert"
 	"github.com/stretchr/testify/require"
-	"go.uber.org/mock/gomock"
```
Comment (ccoVeille) [inline pkg/gofr/container/container_test.go:10]: this line should remain, there is no reason to have a distinct block for gomock before the github.com packages

File: pkg/gofr/container/datasources.go [hunk 2]
```diff
@@ -5,13 +5,12 @@ import (
 	"database/sql"
 
 	"github.com/redis/go-redis/v9"
+	gofrSQL "gofr.dev/pkg/gofr/datasource/sql"
 
 	"gofr.dev/pkg/gofr/datasource"
-	gofrSQL "gofr.dev/pkg/gofr/datasource/sql"
```
Comment (ccoVeille) [inline pkg/gofr/container/datasources.go:10]: same here

File: pkg/gofr/container/health_test.go [hunk 3]
```diff
@@ -9,7 +9,6 @@ import (
 	"testing"
 
 	"github.com/stretchr/testify/assert"
-
```
Comment (ccoVeille) [inline pkg/gofr/container/health_test.go:12]: you should not remove this line

I'm surprised gci linter didn't report an issue

https://github.com/gofr-dev/gofr/blob/eedaec521dac7b4d624b7f4cab510e8eab9fde11/.golangci.yml#L10-L14

File: pkg/gofr/container/mock_container.go [hunk 4]
```diff
@@ -2,10 +2,14 @@ package container
...
 	"fmt"
 	"net/http"
 	"testing"
 
+	"github.com/DATA-DOG/go-sqlmock"
+	"gofr.dev/pkg/gofr/datasource/sql"
+
 	"go.uber.org/mock/gomock"
 
 	"gofr.dev/pkg/gofr/datasource"
```
Comment (ccoVeille) [inline pkg/gofr/container/mock_container.go:15]: Please install [gci](https://github.com/daixiang0/gci/) and run

```shell
gci write -s standard -s default -s localmodule .
```

File: pkg/gofr/container/mock_container.go [hunk 5]
```diff
@@ -75,7 +114,114 @@ func NewMockContainer(t *testing.T) (*Container, Mocks) {
...
+		m.logger.Fatalf("expected query: %s, actual query: %s", query, expectedText)
+	}
+
+	if len(args) != len(expectedArgs) {
+		m.logger.Fatalf("expected %d args, actual %d", len(expectedArgs), len(args))
+	}
+
+	for i := range args {
+		if args[i] != expectedArgs[i] {
+			m.logger.Fatalf("expected arg %d, actual arg %d", args[i], expectedArgs[i])
```
Comment (ccoVeille) [inline pkg/gofr/container/mock_container.go:136]: maybe error would be enough here

```suggestion
			m.logger.Errorf("expected arg %d, actual arg %d", args[i], expectedArgs[i])
```

This way the error message will be clearer if something fails

File: pkg/gofr/container/mockcontainer_test.go [hunk 6]
```diff
@@ -0,0 +1 @@
+package container
```
Comment (ccoVeille) [inline pkg/gofr/container/mockcontainer_test.go:1]: why adding this empty file ?

did you plan to add tests and forgot them ?

File: pkg/gofr/container/mock_container.go [hunk 7]
```diff
@@ -75,7 +114,114 @@ func NewMockContainer(t *testing.T) (*Container, Mocks) {
...
+	}
+
+	m.queryWithArgs = m.queryWithArgs[:lastIndex]
+}
+
+func (m sqlMockDB) HealthCheck() *datasource.Health {
+	if m.expectedHealthCheck == nil || len(m.expectedHealthCheck) == 0 {
+		m.logger.Fatal("Did not expect any mock calls for HealthCheck")
+	}
+
```
Comment (ccoVeille) [inline pkg/gofr/container/mock_container.go:147]: I'm surprised this file and a few others do not use testify but plain testing

I mean here, I would have expected something like this

```suggestion
	require.NotEmpty(m.expectedHealthCheck, "Did not expect any mock calls for HealthCheck")
```

File: pkg/gofr/migration/sql_test.go [hunk 8]
```diff
@@ -4,123 +4,153 @@ import (
...
+		mocks.SQL.ExpectExec("DELETE FROM users WHERE id = ?").WithArgs(1).WillReturnResult(expectedResult)
+		sqlDB := mockContainer.SQL
 
 		result, err := sqlDB.Exec("DELETE FROM users WHERE id = ?", 1)
+		require.NoError(t, err)
 
-		if err != nil {
-			t.Errorf("Exec should return no error, got: %v", err)
-		}
+		expectedLastInserted, err := expectedResult.LastInsertId()
```
Comment (ccoVeille) [inline pkg/gofr/migration/sql_test.go:132]: a last insertid on a delete ?

I understand everything is mocked but it's strange

**Review by ccoVeille — APPROVED** [review]
sounds good except a few minor things

File: pkg/gofr/container/mock_container.go (hunk 5 above)
Comment (coolwednesday) [reply pkg/gofr/container/mock_container.go:136]: Here, I would like to stop the execution instead of just an error log, as proceeding even after the query and arguments of the function do not match, would not be the ideal behaviour in case of sqlmocks.

File: pkg/gofr/container/mockcontainer_test.go (hunk 6 above)
Comment (coolwednesday) [reply pkg/gofr/container/mockcontainer_test.go:1]: Sorry for the confusion , I forgot to push the recent changes.

File: pkg/gofr/container/mock_container.go (hunk 5 above)
Comment (ccoVeille) [reply pkg/gofr/container/mock_container.go:136]: OK, indeed

File: pkg/gofr/container/mockcontainer_test.go (hunk 6 above)
Comment (ccoVeille) [reply pkg/gofr/container/mockcontainer_test.go:1]: 😂👍

File: pkg/gofr/container/mock_container.go (hunk 7 above)
Comment (coolwednesday) [reply pkg/gofr/container/mock_container.go]: I don't pass the t *Testing.T in the functions that is required for require and assert functions.

File: pkg/gofr/migration/sql_test.go [hunk 9]
```diff
@@ -4,123 +4,153 @@ import (
...
-			t.Errorf("Query should return the expected rows, got: %v", rows)
+		for rows.Next() {
+			err = rows.Scan(&id, &name)
+			require.NoError(t, err)
+			require.NoError(t, rows.Err())
+			assert.Equal(t, expectedResult[i].id, id)
+			assert.Equal(t, expectedResult[i].name, name)
+
+			i++
 		}
```
Comment (ccoVeille) [inline pkg/gofr/migration/sql_test.go:51]: I know these are tests, but usually after a `for rows->Next` loop

It's a good thing to check if rows->Error() don't return an error

File: pkg/gofr/migration/sql_test.go [hunk 10]
```diff
@@ -4,123 +4,153 @@ import (
...
-			t.Errorf("Query should return the expected error, got: %v", err)
+		rows, err := sqlMockDB.Query("SELECT * FROM unknown_table")
+		require.NoError(t, err)
+
+		for rows.Next() {
+			err = rows.Scan(&id, &name)
+			require.NoError(t, rows.Err())
+			require.Error(t, err)
+			assert.Equal(t, expectedErr, err)
 		}
```
Comment (ccoVeille) [inline pkg/gofr/migration/sql_test.go:74]: Same remark

https://github.com/gofr-dev/gofr/pull/988#discussion_r1744867529

File: pkg/gofr/migration/sql_test.go (hunk 8 above)
Comment (coolwednesday) [reply pkg/gofr/migration/sql_test.go:132]: I suppose Last insertID does not change with a delete query...but as all exec commands return Result that has last inserted and rowsAffected .....I think a non-zero value would be returned. I might be wrong....but I can't find any definite answer about this, around on the internet.

File: pkg/gofr/container/container_test.go [hunk 11]
```diff
@@ -160,15 +160,16 @@ func TestContainer_Close(t *testing.T) {
...
 	mockRedis := NewMockRedis(controller)
 	mockPubSub := &MockPubSub{}
 
-	mockDB.EXPECT().Close().Return(nil)
 	mockRedis.EXPECT().Close().Return(nil)
+	sqlMock.ExpectClose()
 
 	c := NewContainer(config.NewMockConfig(nil))
-	c.SQL = mockDB
+	c.SQL = &sqlMockDB{mockDB, &e, logging.NewLogger(logging.DEBUG)}
```
Comment (Umang01-hash) [inline pkg/gofr/container/container_test.go:172]: Can we not directly write it like this? Is there any specific need of variable `e` ?

`c.SQL = &sqlMockDB{mockDB, &expectedQuery{}, logging.NewLogger(logging.DEBUG)}`

File: pkg/gofr/container/mock_container.go [hunk 12]
```diff
@@ -32,8 +33,16 @@ func NewMockContainer(t *testing.T) (*Container, Mocks) {
 
 	ctrl := gomock.NewController(t)
 
-	sqlMock := NewMockDB(ctrl)
-	container.SQL = sqlMock
+	mockDB, sqlMock, _ := sql.NewSQLMocks(t)
+	// initialisation of expectations
+	e := expectedQuery{}
+
+	sql2 := &mockSQL{sqlMock, &e}
```
Comment (Umang01-hash) [inline pkg/gofr/container/mock_container.go:40]: `sql2` name is not very clear. Maybe we can name it to `sqlMockWrapper`, `testSQLMock` or anything more relevant?

File: pkg/gofr/container/mock_container.go [hunk 13]
```diff
@@ -32,8 +33,16 @@ func NewMockContainer(t *testing.T) (*Container, Mocks) {
 
 	ctrl := gomock.NewController(t)
 
-	sqlMock := NewMockDB(ctrl)
-	container.SQL = sqlMock
+	mockDB, sqlMock, _ := sql.NewSQLMocks(t)
+	// initialisation of expectations
+	e := expectedQuery{}
```
Comment (Umang01-hash) [inline pkg/gofr/container/mock_container.go:38]: No need of this variable, just use `expectedQuery` struct inside `&mockSQL{}`

File: pkg/gofr/container/mockcontainer_test.go [hunk 14]
```diff
@@ -0,0 +1,47 @@
...
+	"context"
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+
+	"gofr.dev/pkg/gofr/datasource"
+)
+
+func TestMockSQL_Select(t *testing.T) {
+	ids := make([]string, 0)
```
Comment (Umang01-hash) [inline pkg/gofr/container/mockcontainer_test.go:13]: Why not to use this instead?
`ids := []string{"1", "2"}`

File: pkg/gofr/container/sql_mock.go [hunk 15]
```diff
@@ -0,0 +1,163 @@
+package container
+
+import (
+	"context"
+	gosql "database/sql"
```
Comment (Umang01-hash) [inline pkg/gofr/container/sql_mock.go:5]: Instead of adding alias to the official library, let's add it to our GoFr Sql package.

File: pkg/gofr/migration/sql_test.go [hunk 16]
```diff
@@ -4,123 +4,153 @@ import (
...
+
+		i := 0
 
-		if rows != expectedRows {
-			t.Errorf("Query should return the expected rows, got: %v", rows)
+		for rows.Next() {
+			err = rows.Scan(&id, &name)
+			require.NoError(t, err)
+			require.NoError(t, rows.Err())
+			assert.Equal(t, expectedResult[i].id, id)
```
Comment (Umang01-hash) [inline pkg/gofr/migration/sql_test.go:47]: We can use replace all the `assert` with `require` so as to use only one of them for tests.

**Review by Umang01-hash — CHANGES_REQUESTED** [review]

File: pkg/gofr/container/container_test.go (hunk 11 above)
Comment (coolwednesday) [reply pkg/gofr/container/container_test.go:172]: I am initialising a struct and then I am passing the pointer to the same struct in mocksql as well as mocksqlDB. S I intialised it seperately. Though I will change e to a better variable name.

**Review by Umang01-hash — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]
