### PR TITLE
Fixing Improper-sqlite-logs

### LINKED ISSUE #968: Improper logs  in sqlite db
When connecting to sqlite db - logs are coming incorrectly.

Port and host are coming in spite of no port and host required.

To Reproduce: Connect with the following configs - 
DB_DIALECT=sqlite
DB_NAME=test

### PR DESCRIPTION
**Pull request by coolwednesday**
- Made functions to log to handle sqlite db case separately.
- Closes #968 

Screenshot 2024-09-27 at 12 13 53 PM

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

File: pkg/gofr/datasource/sql/sql_test.go [hunk 1]
```diff
@@ -256,6 +257,50 @@ func Test_NewSQLMockWithConfig(t *testing.T) {
...
+		expectedLog string
+	}{
+		{"sqlite connection in process", "connecting", nil, `connecting to 'test' database`},
+		{"sqlite connected successfully", "connected", nil, `connected to 'test' database`},
+		{"sqlite connection failure", "", errSqliteConnection,
+			`could not connect to database 'test', error: connection failed`},
+	}
+
+	for _, test := range tests {
+		if test.err == nil {
```
Comment (Umang01-hash) [inline pkg/gofr/datasource/sql/sql_test.go:276]: Instead of having an `if-else` statement in test , it's better to break down it into two test methods one for error case and one for success case

File: examples/http-server/configs/.env [hunk 2]
```diff
@@ -11,4 +11,4 @@ DB_NAME=test
 DB_PORT=2001
 DB_DIALECT=mysql
 
-TRACE_EXPORTER=gofr
+TRACE_EXPORTER=gofr
```
Comment (Umang01-hash) [inline examples/http-server/configs/.env:14]: Why have we added this change here?

**Review by Umang01-hash — CHANGES_REQUESTED** [review]

**Review by Umang01-hash — DISMISSED** [review]

**Review by vipul-rawat — COMMENTED** [review]
Can we do this with the pretty print interface and using log struct, is that a feisable solution?
@aryanmehrotra

**Review by vipul-rawat — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]

**Review by Umang01-hash — APPROVED** [review]
