### PR TITLE
Fix: Disconnected Spans exported for Remote-log-url

### LINKED ISSUE #1278: Disconnected Spans are exported to the remote-log-url
**Describe the bug**
Disconnected spans are found when we set a remote-log-url

**Expected behavior**
It is necessary to Identify the connected spans and ensuring they have the same trace-id.

**Screenshots**
[
Screenshot 2024-12-06 at 6 36 17 PM
](url)

### PR DESCRIPTION
**Pull request by coolwednesday**
## Pull Request Template

**Description:**

- Closes #1278 
- Previously disconnected spans were created for each fetch request of the remote log .....
- The change in code makes sure that the all the traces exported for one http-request has spans in hierarchy.
- It also makes sure that we don't export retry connection logs for sql connection, as it is not a developer concern. Logs will be suffice in such case.

Screenshot 2024-12-09 at 1 46 45 PM

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

File: pkg/gofr/exporter.go [hunk 1]
```diff
@@ -96,6 +96,10 @@ func convertSpans(spans []sdktrace.ReadOnlySpan) []Span {
 	convertedSpans := make([]Span, 0, len(spans))
 
 	for i, s := range spans {
+		if s.Name() == "sql.connector.connect" {
```
Comment (Umang01-hash) [inline pkg/gofr/exporter.go:99]: can we use a constant here instead of this hard-coded string?

File: pkg/gofr/service/new.go [hunk 2]
```diff
@@ -137,12 +137,14 @@ func (h *httpService) createAndSendRequest(ctx context.Context, method string, p
...
-	spanContext, span := h.Tracer.Start(ctx, uri)
+	ctx, span := h.Tracer.Start(ctx, uri)
 	defer span.End()
 
-	spanContext = httptrace.WithClientTrace(spanContext, otelhttptrace.NewClientTrace(ctx))
+	// Attach client-side trace handling for HTTP request
+	clientTraceCtx := httptrace.WithClientTrace(ctx, otelhttptrace.NewClientTrace(ctx))
 
-	req, err := http.NewRequestWithContext(spanContext, method, uri, bytes.NewBuffer(body))
+	// Create the HTTP request with the tracing context
```
Comment (Umang01-hash) [inline pkg/gofr/service/new.go:146]: Here and everywhere we have added new comments, we should make sure that they end with a period (.)

**Review by Umang01-hash — CHANGES_REQUESTED** [review]

**Review by Umang01-hash — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]

**Review by Umang01-hash — APPROVED** [review]
