### PR TITLE
fix math.Nan() return bug by placing correct encoding failure status …

### LINKED ISSUE #2739: HTTP Responder silently fails in case of math.NaN() is returned
**Describe the bug**
json encoder fails inside responder when math.NaN() comes to be marshalled

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

```
func HelloHandler(c *gofr.Context) (any, error) {
	return math.NaN(), nil
}   
   ```

2. The error is

Status Code is set as 200, but the server fails to give response neither there is any log as

```
// Respond sends a response with the given data and handles potential errors, setting appropriate
// status codes and formatting responses as JSON or raw data as needed.
func (r Responder) Respond(data any, err error) {
	if r.handleSpecialResponseTypes(data, err) {
		return
	}

	statusCode, errorObj := r.determineResponse(data, err)

	var resp any

	switch v := data.(type) {
	case resTypes.Raw:
		resp = v.Data
	case resTypes.Response:
		resp = response{Data: v.Data, Metadata: v.Metadata, Error: errorObj}
	default:
		// handling where an interface contains a nullable type with a nil value.
		if isNil(data) {
			data = nil
		}

		resp = response{Data: data, Error: errorObj}
	}

	if r.w.Header().Get("Content-Type") == "" {
		r.w.Header().Set("Content-Type", "application/json")
	}

	r.w.WriteHeader(statusCode)

	_ = json.NewEncoder(r.w).Encode(resp) -> Error not being handled here
}
```

**Expected behavior**
Since golang support math.NaN() gofr should also support handling it, and in anycase server should tell the user and set the correct status code when anything like this happens

**Screenshots**
Image

### PR DESCRIPTION
**Pull request by Umang01-hash**
## Pull Request Template

**Description:**

-   Fixes #2739.
- Pre-encode responses using `json.Marshal()` before writing HTTP status code. If encoding fails (NaN, Inf, channels, functions), r**eturn HTTP 500 with error message.** 
- Added explicit newline (`\n`) after `json.Marshal()` output to maintain backwards compatibility with existing `json.Encoder.Encode()` behavior.

Screenshot 2025-12-29 at 12 12 09 PM

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

File: pkg/gofr/http/responder.go [hunk 1]
```diff
@@ -53,9 +53,22 @@ func (r Responder) Respond(data any, err error) {
...
+
+		errorResp := response{Error: map[string]any{"message": "failed to encode response as JSON"}}
+		errorJSON, _ := json.Marshal(errorResp)
 
-	_ = json.NewEncoder(r.w).Encode(resp)
+		_, _ = r.w.Write(errorJSON)
+		_, _ = r.w.Write([]byte("\n"))
+
+		return
+	}
```
Comment (ccoVeille) [inline pkg/gofr/http/responder.go]: You are ignoring the error maybe you could simply hardcore things

Comment (ccoVeille) [inline pkg/gofr/http/responder.go:63]: What about this

```go
        if encodeErr != nil { 
                 r.w.WriteHeader(http.StatusInternalServerError) 
                 _, _ = r.w.Write([]byte(`{"error":{"message": "failed to encode response as JSON"}}`+"\n"))
                 return 
         }

File: pkg/gofr/http/responder_test.go [hunk 2]
```diff
@@ -533,3 +534,71 @@ func TestResponder_XMLFileTemplate_ErrorStatusCodes(t *testing.T) {
...
+		assert.Equal(t, tc.expectedCode, result.StatusCode, "TEST[%d] Failed: %s", i, tc.desc)
+
+		body := new(bytes.Buffer)
+		_, err := body.ReadFrom(result.Body)
+
+		require.NoError(t, err, "TEST[%d] Failed: %s", i, tc.desc)
+
+		assert.NotEmpty(t, body.String(), "TEST[%d] Failed: %s", i, tc.desc)
+
+		result.Body.Close()
```
Comment (ccoVeille) [inline pkg/gofr/http/responder_test.go]: The error is never checked, but also the body is not closed if a require fails above this line.

Please consider adding a t.Cleanup

File: pkg/gofr/http/responder.go (hunk 1 above)
Comment (Umang01-hash) [reply pkg/gofr/http/responder.go:63]: Sure done

File: pkg/gofr/http/responder_test.go (hunk 2 above)
Comment (Umang01-hash) [reply pkg/gofr/http/responder_test.go]: Sure added and updated the test.

File: pkg/gofr/http/responder.go [hunk 3]
```diff
@@ -53,9 +53,18 @@ func (r Responder) Respond(data any, err error) {
...
+		r.w.WriteHeader(http.StatusInternalServerError)
+
+		_, _ = r.w.Write([]byte(`{"error":{"message": "failed to encode response as JSON"}}` + "\n"))
+
+		return
+	}
 
-	_ = json.NewEncoder(r.w).Encode(resp)
+	r.w.WriteHeader(statusCode)
+	_, _ = r.w.Write(jsonData)
```
Comment (ccoVeille) [inline pkg/gofr/http/responder.go:66]: It's a bit out of the scope of the PR, but do you have a way like a logger to report you got an error when writting to output.

Usually, it's a connection closed issue, but it could be interesting to catch them

File: pkg/gofr/http/responder_test.go [hunk 4]
```diff
@@ -533,3 +534,73 @@ func TestResponder_XMLFileTemplate_ErrorStatusCodes(t *testing.T) {
...
+	for i, tc := range tests {
+		recorder := httptest.NewRecorder()
+		responder := NewResponder(recorder, http.MethodGet)
+
+		responder.Respond(tc.data, nil)
+
+		result := recorder.Result()
+
+		t.Cleanup(func() {
+			result.Body.Close()
```
Comment (ccoVeille) [inline pkg/gofr/http/responder_test.go]: This maybe

```suggestion
			require.NoError(t, result.Body.Close())
```

File: pkg/gofr/http/responder.go (hunk 3 above)
Comment (Umang01-hash) [reply pkg/gofr/http/responder.go:66]: @ccoVeille  Great observation! However, **Write errors (connection closed, broken pipe, etc.)** occur after we've successfully set the correct status code and are unrecoverable at this point. 
Adding a logger would require modifying the `NewResponder` factory and struct signature for minimal value, since these transport-layer failures are already tracked by `net/http` and typically represent non-actionable client disconnections.

File: pkg/gofr/http/responder_test.go (hunk 4 above)
Comment (Umang01-hash) [reply pkg/gofr/http/responder_test.go]: done

File: pkg/gofr/http/responder.go (hunk 3 above)
Comment (ccoVeille) [reply pkg/gofr/http/responder.go:66]: Indeed. Thanks for the detailed reply

**Review by coolwednesday — APPROVED** [review]
