### PR TITLE
Fix/pubsub retry

### LINKED ISSUE #1471: MQTT & other PubSubs does not try reconnection after intial connection failiure.
We must add a retry logic for connecting to the pubsub in case of initial connection failiure.

### PR DESCRIPTION
**Pull request by Umang01-hash**
## Pull Request Template

**Description:**

-   Closes #1471.
-   Introduces `retryConnect` to keep trying to connect to broker even if failure at first attempt with a default interval of **10 seconds.**

Screenshot 2025-02-12 at 5 07 46 PM

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

File: pkg/gofr/datasource/pubsub/mqtt/mqtt.go [hunk 1]
```diff
@@ -75,14 +76,15 @@ func New(config *Config, logger Logger, metrics Metrics) *MQTT {
...
 	// create the client using the options above
 	client := mqtt.NewClient(options)
+
 	if token := client.Connect(); token.Wait() && token.Error() != nil {
 		logger.Errorf("could not connect to MQTT at '%v:%v', error: %v", config.Hostname, config.Port, token.Error())
 
-		return &MQTT{Client: client, config: config, logger: logger, mu: mu, metrics: metrics}
+		go retryConnect(client, config, logger, options)
+	} else {
+		logger.Infof("connected to MQTT at '%v:%v' with clientID '%v'", config.Hostname, config.Port, options.ClientID)
```
Comment (coolwednesday) [inline pkg/gofr/datasource/pubsub/mqtt/mqtt.go:85]: this retry connection function also needs to handle connections to default broker ....

**Comment by coolwednesday** [comment]
@Umang01-hash, Also Kafka is not able to subscribe again after losing connection.

**Review by coolwednesday — CHANGES_REQUESTED** [review]

File: pkg/gofr/datasource/pubsub/kafka/kafka.go [hunk 2]
```diff
@@ -269,3 +275,40 @@ func (k *kafkaClient) CreateTopic(_ context.Context, name string) error {
...
+
+		reader := make(map[string]Reader)
+
+		logger.Logf("connected to Kafka broker '%s'", conf.Broker)
+
+		client.conn = conn
+		client.dialer = dialer
+		client.writer = writer
+		client.reader = reader
+
```
[the remark this answers is not in the document]
Comment (Umang01-hash) [reply pkg/gofr/datasource/pubsub/kafka/kafka.go]: done

File: pkg/gofr/datasource/pubsub/mqtt/mqtt.go (hunk 1 above)
Comment (Umang01-hash) [reply pkg/gofr/datasource/pubsub/mqtt/mqtt.go:85]: will raise a different PR for addressing this.

**Review by coolwednesday — APPROVED** [review]

**Review by coolwednesday — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]
