### PR TITLE
Fix Websocket Infinite Write Retry on Closed Connection

### LINKED ISSUE #1527: BUG: When using websocket connetion gofr is using closed connection
**Describe the bug**
When using the below code to use websocket connection

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   package main

import (
	"github.com/gorilla/websocket"
	"gofr.dev/pkg/gofr"
)

func main() {
	app := gofr.New()

	app.WebSocket("/ws", WSHandler)

	app.Run()
}

func WSHandler(ctx *gofr.Context) (any, error) {
	conn := ctx.GetConnectionFromContext(ctx)
	defer conn.Close()

	conn.WriteMessage(websocket.TextMessage, []byte("Hello, World!"))

	return nil, nil
}

   ```

2. The error is

Image

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
- OS: [e.g. Linux]
- gofr version [e.g. v1.5.0]
- go version [e.g. 1.21]

**More description**

### PR DESCRIPTION
**Pull request by coolwednesday**
- Closes #1527

### CODE REVIEW

**Review by Umang01-hash — APPROVED** [review]

File: pkg/gofr/context.go [hunk 1]
```diff
@@ -83,7 +86,15 @@ func (c *Context) WriteMessageToSocket(data any) error {
 		return err
 	}
 
-	return conn.WriteMessage(websocket.TextMessage, message)
+	err = conn.WriteMessage(websocket.TextMessage, message)
+	if err != nil {
+		if websocket.IsCloseError(err, websocket.CloseNormalClosure, websocket.CloseGoingAway,
+			websocket.CloseAbnormalClosure) || errors.Is(err, net.ErrClosed) {
+			fmt.Printf("failed to write message to websocket: %v", err)
```
Comment (aryanmehrotra) [inline pkg/gofr/context.go:93]: why fmt.Printf ?

**Review by aryanmehrotra — CHANGES_REQUESTED** [review]

File: pkg/gofr/context.go (hunk 1 above)
Comment (coolwednesday) [reply pkg/gofr/context.go:93]: removed the log and returning the error directly.

**Review by aryanmehrotra — APPROVED** [review]
