### PR TITLE
Circuit breaker causing HTTP requests to execute sequentially instead of in parallel

### LINKED ISSUE #2889: Circuit Breaker causes parallel requests to execute sequentially
**Describe the bug**
When the circuit breaker is enabled, HTTP requests that normally execute in parallel start behaving sequentially.

For example, Without the circuit breaker, two simultaneous requests complete in ~10 seconds total. After enabling the circuit breaker, the same two requests take ~20 seconds total, indicating that the second request waits for the first one to finish.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   &gofrService.CircuitBreakerConfig{Threshold: 6, Interval: 5 * time.Second}
   ```

**Screenshots**

### 1️⃣ Without Circuit Breaker (Parallel Execution)
Without CB

### 2️⃣ With Circuit Breaker Enabled (Sequential Execution)
With CB

First Image (without CB): Both requests complete in ~10s and total time is ~10s, confirming parallel execution.
Second Image (with CB): One request completes at ~10s and the other at ~20s, total time ~20s, showing the circuit breaker caused sequential execution.

**Environments **
- gofr version 1.25.0
- go version 1.54.0

### PR DESCRIPTION
**Pull request by Umang01-hash**
## Pull Request Template

**Description:**

-   Resolves #2889
-   The `executeWithCircuitBreaker()` function held a mutex lock **during the entire HTTP request execution**, blocking all concurrent requests from proceeding.

```go
Request 1 enters executeWithCircuitBreaker(), acquires the mutex lock
Request 2 tries to enter, blocks waiting for the lock
Request 1 makes the HTTP call (takes 10s) while holding the lock 🔴
Request 1 releases lock after completion
Request 2 finally acquires lock and makes its call (takes another 10s)
Result: Sequential execution (20s total) instead of parallel (10s total)
```

-   Fix: Release mutex BEFORE making the HTTP request, Acquire mutex AFTER the HTTP request completes

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

File: pkg/gofr/service/circuit_breaker.go [hunk 1]
```diff
@@ -60,33 +60,35 @@ func NewCircuitBreaker(config CircuitBreakerConfig, h HTTP) *circuitBreaker {
...
+	defer cb.mu.Unlock()
+
 	if err != nil || (result != nil && result.StatusCode > 500) {
 		cb.handleFailure()
+
+		if cb.failureCount > cb.threshold {
+			cb.openCircuit()
+
+			return nil, ErrCircuitOpen
+		}
```
Comment (coolwednesday) [inline pkg/gofr/service/circuit_breaker.go:85]: The `cb.handleFailure()` method (called on line 81) already checks the threshold and calls `cb.openCircuit()` if necessary. Calling `cb.openCircuit()` again here is redundant and may result in duplicate metrics being recorded for the same circuit break event.

**Suggestion:** 
Simplify the block to only check the state change:
```go
cb.handleFailure()

if cb.state == OpenState {
    return nil, ErrCircuitOpen
}
```
