### PR TITLE
Rearranging Middlewares to allow Authentication before setting WebSocket Conn

### LINKED ISSUE #1526: Cannot Close websocket conneciton in case of unauthorised request
**Describe the bug**
I have validations set for my server to authorise users based on Bearer tokens, when using the websocket, The server is showing connection successfull and I get error logs for connection highjack because I am writing 401 errors to the response writter. 

Even If I ignore the un-authorized request and not move forward, the connection remains open.

**To Reproduce**
Add a middleware which returns and writes to the http.ResponseWriter and hijack can be reproduced.
Check for authorization and return without calling inner.ServeHTTP(w,r), the connection to websocket remains open.

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**
I should be able to get the connection in middleware for the particular websocket request and close connection in case of unauthorised request

**Screenshots**

**Environments (please complete the following information):**
- OS: [e.g. Linux]
- gofr version [e.g. v1.5.0]
- go version [e.g. 1.21]

**More description**

### PR DESCRIPTION
**Pull request by coolwednesday**
- Closes #1526 
- As websocket connection does not inherently provide authentication support. It is favourable to authenticate before starting a websocket connection. This can only be done, if user's added authentication or other middlewares are executed before, upgrading to a websocket connection. This PR addresses the same.

### CODE REVIEW

**Review by Umang01-hash — CHANGES_REQUESTED** [review]

**Review by Umang01-hash — APPROVED** [review]

File: pkg/gofr/run.go [hunk 1]
```diff
@@ -19,6 +21,18 @@ func (a *App) Run() {
...
+	//	WebSocket connections do not inherently support authentication mechanisms.
+	//	It is recommended to authenticate users before upgrading to a WebSocket connection.
+	//	Hence, we are registering middlewares here, to ensure that authentication or other
+	//	middleware logic is executed during the initial HTTP handshake request, prior to upgrading
+	//	the connection to WebSocket.
+	if a.httpServer != nil {
+		a.httpServer.router.Use(middleware.WSHandlerUpgrade(a.container, a.httpServer.ws))
+		a.httpServer.router.Use(middleware.Logging(a.Logger()))
+		a.httpServer.router.Use(middleware.Metrics(a.Metrics()))
+	}
```
Comment (aryanmehrotra) [inline pkg/gofr/run.go:34]: When other default middleware's are being registered in httpServer, we should not be registering any default middleware here.

**Review by aryanmehrotra — CHANGES_REQUESTED** [review]

File: pkg/gofr/run.go (hunk 1 above)
Comment (coolwednesday) [reply pkg/gofr/run.go:34]: I have added a developer note ... explaining the necessity to register it here ....

**Review by aryanmehrotra — DISMISSED** [review]

**Review by aryanmehrotra — DISMISSED** [review]

File: pkg/gofr/context_test.go [hunk 2]
```diff
@@ -78,42 +79,40 @@ func TestContext_AddTrace(t *testing.T) {
...
 	defer ws.Close()
 
 	_, message, err := ws.ReadMessage()
-	require.NoError(t, err)
+	require.NoError(t, err, "Failed to read WebSocket message")
 
-	expectedResponse := "Hello! GoFr"
-	assert.Equal(t, expectedResponse, string(message))
+	expected := "Hello! GoFr"
+	assert.Equal(t, expected, string(message))
```
Comment (Umang01-hash) [inline pkg/gofr/context_test.go:115]: I think instead of using the expected variable we can directly compare the strings here.

File: pkg/gofr/context_test.go [hunk 3]
```diff
@@ -78,42 +79,40 @@ func TestContext_AddTrace(t *testing.T) {
...
 
 		// TODO: returning error here to close the connection to the websocket
 		// as the websocket close error is not caught because we are using no bind function here.
 		// this must not be necessary. We should put an actual check in handleWebSocketConnection method instead.
-		return nil, &websocket.CloseError{Code: websocket.CloseNormalClosure, Text: "Error closing"}
+		return "", &websocket.CloseError{Code: websocket.CloseNormalClosure, Text: "Closing"}
 	})
 
 	go app.Run()
+	time.Sleep(200 * time.Millisecond) // Wait for the server to boot
```
Comment (Umang01-hash) [inline pkg/gofr/context_test.go:101]: Can we use a lesser sleep time maybe `100 milliseconds`?

File: pkg/gofr/http_server_test.go [hunk 4]
```diff
@@ -40,13 +57,13 @@ func TestRun_ServerStartsListening(t *testing.T) {
...
 	// Start the server
-	go server.Run(c)
+	go server.run(c, middleware.GetConfigs(getConfigs(t)))
 
 	// Wait for the server to start listening
 	time.Sleep(100 * time.Millisecond)
 
 	var netClient = &http.Client{
-		Timeout: 200 * time.Millisecond,
+		Timeout: 200 * time.Second,
```
Comment (Umang01-hash) [inline pkg/gofr/http_server_test.go:66]: Can we use a lesser time here also

**Review by Umang01-hash — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]
