### PR TITLE
Fix : Incorrect Logs Displayed for Redis Database Connection Status

### LINKED ISSUE #1323: Incorrect Logs Displayed for Redis Database Connection Status
**Describe the bug**
Even when successfully connected to Redis using configurations, the logs in the screenshot still appear.
Screenshot 2024-12-20 at 1 20 03 PM

**Expected Behavior**
- The logs should not appear if the connection to Redis/SQL is established.
- Additionally, there should be a validation to ensure that if a database connection is established (even without configurations), these logs do not show up.

### PR DESCRIPTION
**Pull request by coolwednesday**
**Description:**

-   Closes #1323 
-   Even though the issue was found while connecting to Redis, the primary issue was in SQL Logs when no SQL connection was made , hence removed the unnecessary logs in SQL connection process.

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

File: pkg/gofr/datasource/sql/sql.go [hunk 1]
```diff
@@ -37,16 +37,20 @@ type DBConfig struct {
...
 	// if Hostname is not provided, we won't try to connect to DB
 	if dbConfig.Dialect != sqlite && dbConfig.HostName == "" {
-		logger.Debugf("not connecting to database as database configurations aren't available")
+		logger.Errorf("connection to SQL failed: host name is empty.")
 		return nil
 	}
 
+	logger.Debugf("Loaded SQL database configurations from the configuration file")
+
 	logger.Debugf("generating database connection string for '%s'", dbConfig.Dialect)
```
Comment (ccoVeille) [inline pkg/gofr/datasource/sql/sql.go:54]: Can't these consecutive debug entry be merged into one?

File: pkg/gofr/datasource/sql/sql.go [hunk 2]
```diff
@@ -37,16 +37,20 @@ type DBConfig struct {
...
 	dbConfig := getDBConfig(configs)
 
+	if dbConfig.Dialect == "" {
+		return nil
+	}
+
 	// if Hostname is not provided, we won't try to connect to DB
 	if dbConfig.Dialect != sqlite && dbConfig.HostName == "" {
-		logger.Debugf("not connecting to database as database configurations aren't available")
+		logger.Errorf("connection to SQL failed: host name is empty.")
```
Comment (ccoVeille) [inline pkg/gofr/datasource/sql/sql.go:48]: Ypu could add the dialect I'm the error message

**Review by Umang01-hash — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]

**Review by aryanmehrotra — APPROVED** [review]
