### PR TITLE
En/system env overrides others

### LINKED ISSUE #1341: System Env not overriding other envs.
**Describe the bug**
If we set any env at `os` level, then it should override all the other env's like `.env` , `.local.env` etc.
It should basically override the env values set by `APP_ENV `config.

### PR DESCRIPTION
**Pull request by Umang01-hash**
## Pull Request Template

**Description:**

-   Resolve #1341.

**Checklist:**

-   [x] I have formatted my code using  `goimport`  and  `golangci-lint`.
-   [x] All new code is covered by unit tests.
-   [x] This PR does not decrease the overall code coverage.
-   [x] I have reviewed the code comments and documentation for clarity.

**Thank you for your contribution!**

### CODE REVIEW

File: pkg/gofr/config/godotenv.go [hunk 1]
```diff
@@ -64,6 +66,14 @@ func (e *EnvLoader) read(folder string) {
 	} else {
 		e.logger.Infof("Loaded config from file: %v", overrideFile)
 	}
+
+	// Reload system environment variables to ensure they override any previously loaded values
+	for _, envVar := range os.Environ() {
+		keyValue := strings.SplitN(envVar, "=", splitParts)
+		if len(keyValue) == splitParts {
```
Comment (ccoVeille) [inline pkg/gofr/config/godotenv.go:73]: There is a problem with the changes here, not the code but the logic, so maybe with the whole PR

Think about a password with `=` character in it

```dotenv
SECRET="foo="
```

Comment (ccoVeille) [inline pkg/gofr/config/godotenv.go:73]: I don't think you will get a number bigger than 2 with SplitN 2

Is the idea about testing at least equal was present?

File: pkg/gofr/config/godotenv.go [hunk 2]
```diff
@@ -64,6 +66,14 @@ func (e *EnvLoader) read(folder string) {
...
+			os.Setenv(keyValue[0], keyValue[1])
```
Comment (ccoVeille) [inline pkg/gofr/config/godotenv.go:74]: Env parsing is somehow as fun as parsing JSON

You can have quote

```dotenv
FOO="bar" # this is fun
```

You can  have comments

```dotenv
FOO=bar # this is fun
```

You can have commented line

```dotenv
#FOO=bar
```

I would recommend using a well tested lib for this, godotenv is already used here. I'm unsure why you are using os.Environ and try to parse them "manually"

File: pkg/gofr/config/godotenv.go [hunk 3]
```diff
@@ -64,6 +66,14 @@ func (e *EnvLoader) read(folder string) {
 	} else {
 		e.logger.Infof("Loaded config from file: %v", overrideFile)
 	}
+
+	// Reload system environment variables to ensure they override any previously loaded values
+	for _, envVar := range os.Environ() {
+		keyValue := strings.SplitN(envVar, "=", splitParts)
```
[the remark this answers is not in the document]
Comment (Umang01-hash) [reply pkg/gofr/config/godotenv.go:72]: Sure @ccoVeille 
I have refactored the code and used ` strings.Cut` instead.

File: pkg/gofr/config/godotenv.go (hunk 1 above)
Comment (Umang01-hash) [reply pkg/gofr/config/godotenv.go:73]: I have tested this scenario with updated implementation and it's working fine.

Comment (Umang01-hash) [reply pkg/gofr/config/godotenv.go:73]: Updated this code to this:
```go

	// Reload system environment variables to ensure they override any previously loaded values
	for _, envVar := range os.Environ() {
		key, value, found := strings.Cut(envVar, "=")
		if found {
			os.Setenv(key, value)
		}
	}
```

File: pkg/gofr/config/godotenv.go (hunk 2 above)
Comment (Umang01-hash) [reply pkg/gofr/config/godotenv.go:74]: @ccoVeille tried using the **godotenv** library to solve the issue, but since we already used the methods `Load()` and `Overload()` once in the code, it was not able to re-load the system environment variables. Therefore, as per the requirement of the issue, I used the above implementation manually to ensure that the system environment variables are correctly reloaded and override any previously loaded values.

Comment (ccoVeille) [reply pkg/gofr/config/godotenv.go]: You should add a valuable comment like this one in the code.

It's not clear otherwise

File: pkg/gofr/config/godotenv.go (hunk 1 above)
Comment (ccoVeille) [reply pkg/gofr/config/godotenv.go]: Do you tji k you could add these tests to the PR then?

File: pkg/gofr/config/godotenv.go [hunk 4]
```diff
@@ -5,13 +5,15 @@ import (
...
 	"os"
+	"strings"
 
 	"github.com/joho/godotenv"
 )
 
 const (
 	defaultFileName         = "/.env"
 	defaultOverrideFileName = "/.local.env"
+	splitParts              = 2
```
Comment (ccoVeille) [inline pkg/gofr/config/godotenv.go:16]: Are you still using this?

Maybe unused linter could be added to golangci-lint

**Review by ccoVeille — APPROVED** [review]

File: pkg/gofr/config/godotenv.go (hunk 4 above)
Comment (Umang01-hash) [reply pkg/gofr/config/godotenv.go:16]: I have removed the const.

thankyou

**Review by vipul-rawat — APPROVED** [review]
